# Generated by Django 2.2.12 on 2021-11-11 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_userprofile_form_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_id', models.CharField(max_length=10)),
                ('group_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner', to=settings.AUTH_USER_MODEL)),
                ('group_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
